/*
 * Program name: EECS 348 Assignment 3 - CEO Email Priority Queue (improved version)
 * Description:  C++ program that prioritizes emails for a CEO using a hand-written
 *               list-based (vector) MaxHeap used as a priority queue. Processes the
 *               commands EMAIL, NEXT, READ and COUNT from a test file (or stdin).
 * Inputs:       Test file path as argv[1] (optional; stdin is used if omitted).
 *               Lines: EMAIL <sender>,<subject>,<MM-DD-YYYY> | NEXT | READ | COUNT
 * Output:       Terminal output for NEXT (sender/subject/date) and COUNT.
 * Collaborators: <FILL IN: names of people, or "none">
 * Other sources: Base code generated by Claude (Anthropic) and improved by the author
 *               with Claude's suggestions; <FILL IN: second GenAI / URLs if any>
 * Author:       <FILL IN: Firstname Lastname>
 * Creation date: <FILL IN>
 * Revision date: <FILL IN>
 * Revisions:    Added sender enum, arrival-order tie-break, input validation,
 *               comparator consolidation, move semantics, reserve(), '\n' output,
 *               parseEmail() separation, stdin fallback.
 */
#include <cstdio>     // snprintf for formatting dates
#include <fstream>    // std::ifstream for reading the test file
#include <iostream>   // std::cin / std::cout
#include <string>     // std::string
#include <utility>    // std::move, std::swap
#include <vector>     // std::vector backs the heap

// Named priority levels; larger value = read sooner (replaces magic numbers). [GenAI + author]
enum class Sender { OtherPerson = 1, ImportantPerson = 2, Peer = 3, Subordinate = 4, Boss = 5 };

// One email in the CEO's inbox. Stores compact data to save space. [GenAI + author]
class Email {
public:
    Sender sender;        // sender category as an enum (smaller than a string)
    std::string subject;  // subject line
    int dateKey;          // date stored as YYYYMMDD integer (also used for comparison)
    long seq;             // arrival order, used as the final tie-breaker

    // Default constructor so the type is easy to use in containers.
    Email() : sender(Sender::OtherPerson), dateKey(0), seq(0) {}

    // Builds an email from already-validated parts, moving the subject to avoid a copy.
    Email(Sender s, std::string subj, int key, long order)
        : sender(s), subject(std::move(subj)), dateKey(key), seq(order) {}

    // Single place that defines priority: sender rank, then newer date, then earlier arrival.
    static bool hasHigherPriority(const Email& a, const Email& b) {
        if (a.sender != b.sender) return a.sender > b.sender;  // higher category first
        if (a.dateKey != b.dateKey) return a.dateKey > b.dateKey;  // newest date first
        return a.seq < b.seq;  // same category and date: earlier arrival first
    }

    // Returns the date formatted as MM-DD-YYYY for display.
    std::string dateString() const {
        char buf[16];  // enough for "MM-DD-YYYY" plus terminator
        std::snprintf(buf, sizeof(buf), "%02d-%02d-%04d", (dateKey / 100) % 100, dateKey % 100, dateKey / 10000);
        return std::string(buf);  // convert the C buffer to std::string
    }

    // Returns the sender's name for display.
    std::string senderString() const {
        switch (sender) {  // map each enum value back to its text
            case Sender::Boss: return "Boss";
            case Sender::Subordinate: return "Subordinate";
            case Sender::Peer: return "Peer";
            case Sender::ImportantPerson: return "ImportantPerson";
            default: return "OtherPerson";
        }
    }
};

// Max-heap priority queue built from scratch on a vector (list-based). [GenAI + author]
class MaxHeap {
private:
    std::vector<Email> data;  // heap array; element 0 is the highest priority

    static int parent(int i) { return (i - 1) / 2; }  // index of parent node
    static int left(int i) { return 2 * i + 1; }      // index of left child
    static int right(int i) { return 2 * i + 2; }     // index of right child

    // Moves the element at index i up until the heap property holds.
    void siftUp(int i) {
        while (i > 0 && Email::hasHigherPriority(data[i], data[parent(i)])) {  // beats its parent?
            std::swap(data[i], data[parent(i)]);  // swap (uses moves, no string copies)
            i = parent(i);                        // continue from the parent position
        }
    }

    // Moves the element at index i down until the heap property holds.
    void siftDown(int i) {
        int n = static_cast<int>(data.size());  // current number of elements
        while (true) {
            int best = i;  // index of the highest-priority among i and its children
            int l = left(i), r = right(i);  // child indices
            if (l < n && Email::hasHigherPriority(data[l], data[best])) best = l;  // left wins?
            if (r < n && Email::hasHigherPriority(data[r], data[best])) best = r;  // right wins?
            if (best == i) break;  // heap property satisfied
            std::swap(data[i], data[best]);  // push the element down
            i = best;                        // continue from the child position
        }
    }

public:
    void reserve(std::size_t n) { data.reserve(n); }  // pre-allocate to avoid regrowth
    bool empty() const { return data.empty(); }       // true if no emails remain
    int size() const { return static_cast<int>(data.size()); }  // number of unread emails

    // Adds an email (taken by value and moved in, avoiding an extra copy).
    void insert(Email e) {
        data.push_back(std::move(e));                     // append at the end
        siftUp(static_cast<int>(data.size()) - 1);        // restore heap order
    }

    const Email& peek() const { return data.front(); }  // highest-priority email, O(1)

    // Removes the highest-priority email.
    void removeMax() {
        data.front() = std::move(data.back());  // move last element to the root
        data.pop_back();                        // shrink the array
        if (!data.empty()) siftDown(0);         // restore heap order
    }
};

// Reads commands and manages the CEO's inbox. [GenAI + author]
class CEOInbox {
private:
    MaxHeap heap;     // the priority queue of unread emails
    long nextSeq;     // counter giving each email an arrival number

    // Removes leading/trailing whitespace (including '\r' from Windows line endings).
    static std::string trim(const std::string& s) {
        std::size_t a = s.find_first_not_of(" \t\r\n");  // first non-space char
        if (a == std::string::npos) return "";           // all whitespace
        std::size_t b = s.find_last_not_of(" \t\r\n");   // last non-space char
        return s.substr(a, b - a + 1);                   // trimmed text
    }

    // Converts a category name to the enum; returns false if unknown.
    static bool parseSender(const std::string& name, Sender& out) {
        if (name == "Boss") out = Sender::Boss;
        else if (name == "Subordinate") out = Sender::Subordinate;
        else if (name == "Peer") out = Sender::Peer;
        else if (name == "ImportantPerson") out = Sender::ImportantPerson;
        else if (name == "OtherPerson") out = Sender::OtherPerson;
        else return false;  // unrecognized category
        return true;
    }

    // Validates MM-DD-YYYY and converts to YYYYMMDD; returns false if malformed.
    static bool parseDate(const std::string& d, int& key) {
        if (d.size() != 10 || d[2] != '-' || d[5] != '-') return false;  // wrong shape
        for (int i = 0; i < 10; i++) {  // every other character must be a digit
            if (i == 2 || i == 5) continue;
            if (d[i] < '0' || d[i] > '9') return false;
        }
        int mm = (d[0] - '0') * 10 + (d[1] - '0');                                    // month
        int dd = (d[3] - '0') * 10 + (d[4] - '0');                                    // day
        int yyyy = (d[6] - '0') * 1000 + (d[7] - '0') * 100 + (d[8] - '0') * 10 + (d[9] - '0');  // year
        if (mm < 1 || mm > 12 || dd < 1 || dd > 31) return false;  // out-of-range values
        key = yyyy * 10000 + mm * 100 + dd;  // YYYYMMDD
        return true;
    }

    // Parses "<sender>,<subject>,<date>"; returns false (email skipped) if malformed.
    bool parseEmail(const std::string& rest, Email& out) {
        std::size_t c1 = rest.find(',');                                      // first comma
        std::size_t c2 = (c1 == std::string::npos) ? c1 : rest.find(',', c1 + 1);  // second comma
        if (c1 == std::string::npos || c2 == std::string::npos) return false; // missing fields
        Sender s;  // parsed sender
        int key;   // parsed date
        if (!parseSender(trim(rest.substr(0, c1)), s)) return false;  // bad category
        if (!parseDate(trim(rest.substr(c2 + 1)), key)) return false; // bad date
        out = Email(s, trim(rest.substr(c1 + 1, c2 - c1 - 1)), key, nextSeq++);  // build the email
        return true;
    }

public:
    CEOInbox() : nextSeq(0) { heap.reserve(1024); }  // start arrival counter, pre-allocate

    // Executes one command line.
    void processLine(const std::string& rawLine) {
        std::string line = trim(rawLine);  // clean the line
        if (line.empty()) return;          // ignore blank lines

        if (line.compare(0, 6, "EMAIL ") == 0) {  // EMAIL command
            Email e;
            if (parseEmail(line.substr(6), e)) heap.insert(std::move(e));  // add only if valid
        } else if (line == "NEXT") {  // NEXT command: show but do not remove
            if (heap.empty()) {
                std::cout << "There are no emails to read.\n";  // nothing to show
            } else {
                const Email& e = heap.peek();  // top of the heap
                std::cout << "Next email:\n"
                          << "Sender: " << e.senderString() << '\n'
                          << "Subject: " << e.subject << '\n'
                          << "Date: " << e.dateString() << '\n';
            }
        } else if (line == "READ") {  // READ command: remove top silently
            if (!heap.empty()) heap.removeMax();
        } else if (line == "COUNT") {  // COUNT command
            std::cout << "There are " << heap.size() << " emails to read.\n";
        }
    }
};

int main(int argc, char* argv[]) {
    std::ios::sync_with_stdio(false);  // faster I/O (we never mix C and C++ streams)
    CEOInbox inbox;                    // the CEO's inbox
    std::string line;                  // current input line

    if (argc >= 2) {  // a file name was given
        std::ifstream in(argv[1]);  // open the test file
        if (!in) {
            std::cerr << "Could not open file: " << argv[1] << '\n';  // report failure
            return 1;
        }
        while (std::getline(in, line)) inbox.processLine(line);  // process every line
    } else {  // no file: fall back to standard input
        while (std::getline(std::cin, line)) inbox.processLine(line);
    }
    return 0;
}
